name: Creación de Infraestructura

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  terraform_deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Obtener las últimas imágenes por servicio y ambiente
    - name: Obtener últimas imágenes de ECR
      run: |
        # Servicios y ambientes
        SERVICES=("orders-service" "payments-service" "products-service" "shipping-service")
        ENVIRONMENTS=("dev" "staging" "prod")
        AWS_REGION="${{ secrets.AWS_REGION }}"
        AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"

        # Funcion para obtener la ultima imagen de un repositorio
        get_latest_image_tag() {
          local repo=$1
          aws ecr describe-images \
            --repository-name "$repo" \
            --region "$AWS_REGION" \
            --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
            --output text
        }

        # Itera sobre servicios y ambientes
        for SERVICE in "${SERVICES[@]}"; do
          for ENV in "${ENVIRONMENTS[@]}"; do
            REPO_NAME="${SERVICE}-${ENV}"
            LATEST_TAG=$(get_latest_image_tag "$REPO_NAME")
            IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${LATEST_TAG}"
            echo "Última imagen para $REPO_NAME: $IMAGE_URI"
            VAR_NAME="${SERVICE//-/_}_${ENV}_IMAGE_URI"
            echo "$VAR_NAME=$IMAGE_URI" >> $GITHUB_ENV
          done
        done
    
    - name: Configurar Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Inicializar Terraform
      working-directory: terraform
      run: terraform init

    - name: Aplicar Terraform
      run: |
        # Servicios y ambientes
        SERVICES=("orders-service" "payments-service" "products-service" "shipping-service")
        ENVIRONMENTS=("dev" "staging" "prod")

        # Iterar sobre los ambientes
        for ENV in "${ENVIRONMENTS[@]}"; do
          echo "Cambiando al workspace: $ENV"

          # Selecciona o crea el workspace
          terraform workspace new "$ENV"

          # Iterar sobre los servicios
          for SERVICE in "${SERVICES[@]}"; do
            IMAGE_URI_VAR="$${SERVICE//-/_}_${ENV}_IMAGE_URI"
            DOCKER_IMAGE_URI="${!IMAGE_URI_VAR}"  # Obtiene el valor de la variable dinámica

            if [ -z "$DOCKER_IMAGE_URI" ]; then
              echo "ERROR: No se encontró una imagen para $SERVICE en el ambiente $ENV"
              exit 1
            fi

            echo "Aplicando Terraform para $SERVICE en el ambiente $ENV con la imagen $DOCKER_IMAGE_URI"
            terraform apply -auto-approve -var="project=$SERVICE" -var="docker-image=$DOCKER_IMAGE_URI"
          done
        done
